# Generated by Django 6.1.1 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='edge_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='ela_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='frequency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='histogram_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='noise_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='status',
            field=models.CharField(default='Not Analyzed', max_length=50),
        ),
    ]
