# Generated by Django 6.1.1 on 2026-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0002_imageanalysis_analyzed_at_imageanalysis_edge_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='copy_move_score',
            field=models.FloatField(default=0.0),
        ),
    ]
